# Generated by Django 3.2.4 on 2021-06-26 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0001_initial'),
        ('design', '0002_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Design',
        ),
    ]
