# Generated by Django 3.2.4 on 2021-06-26 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0001_initial'),
        ('design', '0003_rename_product_design'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='design',
            options={'ordering': ['-data_added']},
        ),
        migrations.AlterField(
            model_name='design',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='design.category'),
        ),
        migrations.AlterField(
            model_name='design',
            name='designer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='designer.designer'),
        ),
    ]
